# library(jpshanno)
# library(data.table)
# library(ggplot2)
# library(mgcv)
# library(patchwork)
# library(quantreg)
# library(sirad)
# library(sf)
# library(gamm4)

library(data.table)
library(lubridate)
library(ggplot2)
library(purrr)
library(mcp)
library(jpshanno)
library(robustbase)
library(sirad)
library(quantreg)
library(patchwork)
library(ggforce)
library(lme4)
library(parallel)